=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/main/resources/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!ELEMENT mapper (cache-ref | cache | resultMap* | parameterMap* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
namespace CDATA #IMPLIED
>

<!ELEMENT cache-ref EMPTY>
<!ATTLIST cache-ref
namespace CDATA #REQUIRED
>

<!ELEMENT cache (property*)>
<!ATTLIST cache
type CDATA #IMPLIED
eviction CDATA #IMPLIED
flushInterval CDATA #IMPLIED
size CDATA #IMPLIED
readOnly CDATA #IMPLIED
blocking CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)?>
<!ATTLIST parameterMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
resultMap CDATA #IMPLIED
scale CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT resultMap (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST resultMap
id CDATA #REQUIRED
type CDATA #REQUIRED
extends CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
>

<!ELEMENT constructor ((idArg|arg)*)>

<!ELEMENT id EMPTY>
<!ATTLIST id
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT idArg EMPTY>
<!ATTLIST idArg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
name CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
name CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
>

<!ELEMENT collection (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST collection
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
ofType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
notNullColumn CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
resultSet CDATA #IMPLIED
foreignColumn CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
fetchType (lazy|eager) #IMPLIED
>

<!ELEMENT association (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST association
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
notNullColumn CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
resultSet CDATA #IMPLIED
foreignColumn CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
fetchType (lazy|eager) #IMPLIED
>

<!ELEMENT discriminator (case+)>
<!ATTLIST discriminator
column CDATA #IMPLIED
javaType CDATA #REQUIRED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT case (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST case
value CDATA #REQUIRED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
fetchSize CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
useCache (true|false) #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
resultOrdered (true|false) #IMPLIED
resultSets CDATA #IMPLIED 
affectData (true|false) #IMPLIED
>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST selectKey
resultType CDATA #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
keyColumn CDATA #IMPLIED
order (BEFORE|AFTER) #IMPLIED
databaseId CDATA #IMPLIED
>

<!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include (property+)?>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT bind EMPTY>
<!ATTLIST bind
 name CDATA #REQUIRED
 value CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
id CDATA #REQUIRED
lang CDATA #IMPLIED
databaseId CDATA #IMPLIED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
nullable (true|false) #IMPLIED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/xml_references/PersonMapper.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.xml_references.PersonMapper">

    <resultMap id="personMap" type="Person">
        <id property="id" column="id"/>
        <result property="firstName" column="firstName"/>
        <result property="lastName" column="lastName"/>
    </resultMap>


    <sql id="selectByIdScript">
        SELECT id, firstName, lastName, personType
        FROM person
        WHERE id = #{id}
    </sql>
    <select id="selectById" resultMap="personMap" parameterType="int">
        <include refid="selectByIdScript"/>
    </select>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/automapping/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.automapping.Mapper">

    <select id="getUser" resultMap="result">
        select id, name from users where id = #{id}
    </select>

    <resultMap type="org.apache.ibatis.submitted.automapping.User" id="result" autoMapping="true">
    </resultMap>

    <select id="getUserWithPhoneNumber" resultMap="resultWithPhoneNumber">
        select * from users where id = #{id}
    </select>

    <resultMap type="org.apache.ibatis.submitted.automapping.User" id="resultWithPhoneNumber" autoMapping="true">
        <result property="phone" column="phone_number"/>
    </resultMap>

    <sql id="selectUserPetBreeder">
        select users.id, users.name,
            pets.id as petId, pets.name as petName,
            breeder.id as breederId, breeder.name as breederName
        from users
        left join pets on pets.owner = users.id
        left join breeder on breeder.id = pets.breeder
        where users.id = #{id}
    </sql>

    <select id="getUserWithPets_Inline" resultMap="resultWithPets_Inline">
        <include refid="selectUserPetBreeder" />
    </select>

    <resultMap type="org.apache.ibatis.submitted.automapping.User" id="resultWithPets_Inline" autoMapping="true">
        <id column="id" property="id"/>
        <collection property="pets" ofType="org.apache.ibatis.submitted.automapping.Pet">
            <id column="petId" property="petId"/>
            <association property="breeder" javaType="org.apache.ibatis.submitted.automapping.Breeder" autoMapping="true"/>
        </collection>
    </resultMap>

    <select id="getUserWithPets_External" resultMap="resultWithPets_External">
        <include refid="selectUserPetBreeder" />
    </select>

    <resultMap type="org.apache.ibatis.submitted.automapping.User" id="resultWithPets_External" autoMapping="true">
        <id column="id" property="id"/>
        <collection property="pets" resultMap="petResult" />
    </resultMap>

    <resultMap type="org.apache.ibatis.submitted.automapping.Pet" id="petResult">
        <id property="petId" column="petId" />
        <association property="breeder" resultMap="breederResult" />
    </resultMap>

    <resultMap type="org.apache.ibatis.submitted.automapping.Breeder" id="breederResult" autoMapping="true">
        <id property="breederId" column="breederId" />
    </resultMap>

    <resultMap type="org.apache.ibatis.submitted.automapping.Book" id="bookResult">
        <result property="name" column="name"/>
    </resultMap>

    <select id="getBooks" resultMap="bookResult">
        select version, name from books
    </select>

    <select id="getArticle" resultType="org.apache.ibatis.submitted.automapping.Article">
        select 9 as version from INFORMATION_SCHEMA.SYSTEM_USERS
    </select>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/empty_namespace/Person.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="">

    <resultMap id="personMap" type="Person">
        <id property="id" column="id"/>
        <result property="firstName" column="firstName"/>
        <result property="lastName" column="lastName"/>
    </resultMap>


    <select id="selectAllByType" resultMap="personMap" parameterType="org.apache.ibatis.submitted.ognl_enum.Person$Type">
        SELECT id, firstName, lastName, personType
        FROM person
        <where>
            <if test="_parameter != null and _parameter.toString() == 'EMPLOYEE'">
                AND personType = #{type}
            </if>
            <if test="_parameter != null and _parameter.toString() == 'DIRECTOR'">
                AND personType = #{type}
            </if>
        </where>
    </select>
    <select id="selectAllByTypeNameAttribute" resultMap="personMap" parameterType="org.apache.ibatis.submitted.ognl_enum.Person$Type">
        SELECT id, firstName, lastName, personType
        FROM person
        <where>
            <if test="name == 'EMPLOYEE'">
                AND personType = #{type}
            </if>
            <if test="name == 'DIRECTOR'">
                AND personType = #{type}
            </if>
        </where>
    </select>

    <select id="selectAllByTypeWithInterface" resultMap="personMap" parameterType="org.apache.ibatis.submitted.ognl_enum.PersonMapper$PersonType">
        SELECT id, firstName, lastName, personType
        FROM person
        <where>
            <if test="type.toString() == 'EMPLOYEE'">
                AND personType = #{type}
            </if>
            <if test="type.toString() == 'DIRECTOR'">
                AND personType = #{type}
            </if>
        </where>
    </select>
    <select id="selectAllByTypeNameAttributeWithInterface" resultMap="personMap" parameterType="org.apache.ibatis.submitted.ognl_enum.PersonMapper$PersonType">
        SELECT id, firstName, lastName, personType
        FROM person
        <where>
            <if test="type.toString() == 'EMPLOYEE'">
                AND personType = #{type}
            </if>
            <if test="type.toString() == 'DIRECTOR'">
                AND personType = #{type}
            </if>
        </where>
    </select>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/lazy_properties/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.lazy_properties.Mapper">

  <resultMap type="org.apache.ibatis.submitted.lazy_properties.User"
    id="user">
    <id property="id" column="id" />
    <result property="name" column="name" />
  </resultMap>

  <resultMap type="org.apache.ibatis.submitted.lazy_properties.User"
    id="userWithLazyProperties" extends="user">
    <association property="lazy1" column="id" select="getLazy1"
      fetchType="lazy" />
    <association property="lazy2" column="id" select="getLazy2"
      fetchType="lazy" />
    <collection property="lazy3" column="id" select="getLazy3"
      fetchType="lazy" />
  </resultMap>

  <select id="getUser" resultMap="userWithLazyProperties">
    select * from users where id =
    #{id}
  </select>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/nestedresulthandler_association/AccountRepository.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "https://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<mapper namespace="org.apache.ibatis.submitted.nestedresulthandler_association.AccountRepository">
    <resultMap id="resultMapAccount" type="org.apache.ibatis.submitted.nestedresulthandler_association.Account">
        <id property="accountUuid" column="account_uuid" />
        <result property="accountName" column="account_name" />
        <result property="birthDate" column="birth_date" />
        <association property="address" javaType="org.apache.ibatis.submitted.nestedresulthandler_association.AccountAddress">
            <id property="accountUuid" column="account_uuid" />
            <result property="zipCode" column="zip_code" />
            <result property="address" column="address" />
        </association>
    </resultMap>
    <select id="collectPageByBirthMonth" resultMap="resultMapAccount" resultOrdered="true">
        <![CDATA[
        SELECT
          a.account_uuid
          ,a.account_name
          ,a.birth_date
          ,aa.zip_code
          ,aa.address
        FROM
          t_account a
        LEFT OUTER JOIN
          t_account_address aa
            ON aa.account_uuid = a.account_uuid
        WHERE
          a.birth_date >= #{birthMonth} AND a.birth_date < ADD_MONTHS(#{birthMonth}, 1)
        ORDER BY
          a.account_uuid
        ]]>
    </select>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/constructor_columnprefix/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper
  namespace="org.apache.ibatis.submitted.constructor_columnprefix.Mapper">

  <resultMap id="keyRM"
    type="org.apache.ibatis.submitted.constructor_columnprefix.EntityKey">
    <id property="id" column="id" />
  </resultMap>

  <resultMap id="authorRM"
    type="org.apache.ibatis.submitted.constructor_columnprefix.Author">
    <id property="id" column="id" />
  </resultMap>

  <resultMap id="articleRM"
    type="org.apache.ibatis.submitted.constructor_columnprefix.Article">
    <constructor>
      <idArg resultMap="keyRM" columnPrefix="key_"
        javaType="org.apache.ibatis.submitted.constructor_columnprefix.EntityKey" />
      <arg column="name" javaType="string" />
      <arg resultMap="authorRM" columnPrefix="author_"
        javaType="org.apache.ibatis.submitted.constructor_columnprefix.Author" />
      <arg resultMap="authorRM" columnPrefix="coauthor_"
        javaType="org.apache.ibatis.submitted.constructor_columnprefix.Author" />
    </constructor>
  </resultMap>

  <select id="getArticles" resultMap="articleRM"><![CDATA[
    select id key_id, name, author.id author_id, author.name author_name,
      coauthor.id coauthor_id, coauthor.name coauthor_name
    from articles
    left join authors author on author.id = articles.author_id
    left join authors coauthor on coauthor.id = articles.coauthor_id
    order by articles.id
  ]]></select>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/enumtypehandler_on_map/Person.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.enumtypehandler_on_map.PersonMapper">

    <resultMap id="personMap" type="Person">
        <id property="id" column="Person_id"/>
        <result property="firstName" column="Person_firstName"/>
        <result property="lastName" column="Person_lastName"/>
    </resultMap>


    <sql id="columns">
        Person.id AS Person_id,
        Person.firstName AS Person_firstName,
        Person.lastName AS Person_lastName,
        Person.personType AS Person_personType
    </sql>


    <select id="getByType" resultMap="personMap" parameterType="map">
        SELECT <include refid="columns"/>
        FROM Person
        WHERE personType = #{type,jdbcType=VARCHAR}
    </select>
    <select id="getByTypeNoParam" resultMap="personMap" parameterType="org.apache.ibatis.submitted.enumtypehandler_on_map.PersonMapper$TypeName">
        SELECT <include refid="columns"/>
        FROM Person
        WHERE personType = #{type,jdbcType=VARCHAR}
    </select>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/associationtype/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.associationtype.Mapper">

 <resultMap id="sampleHashResult" type="hashmap">
    <result property="f1" column="f1" />
    <result property="f2" column="f2" />
    <association property="a1" javaType="java.lang.String"
        column="{param1=f1}" select="associationTest" />
    <association property="a2" javaType="java.lang.String"
        column="{param1=f1}" select="associationTest" />
    </resultMap>

    <select id="getUser" resultMap="sampleHashResult">
        SELECT id as f1, name as f2 from users
    </select>

    <select id="associationTest" resultType="java.lang.String">
        select id from users
    </select>

</mapper>
