=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/main/resources/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!ELEMENT mapper (cache-ref | cache | resultMap* | parameterMap* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
namespace CDATA #IMPLIED
>

<!ELEMENT cache-ref EMPTY>
<!ATTLIST cache-ref
namespace CDATA #REQUIRED
>

<!ELEMENT cache (property*)>
<!ATTLIST cache
type CDATA #IMPLIED
eviction CDATA #IMPLIED
flushInterval CDATA #IMPLIED
size CDATA #IMPLIED
readOnly CDATA #IMPLIED
blocking CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)?>
<!ATTLIST parameterMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
resultMap CDATA #IMPLIED
scale CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT resultMap (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST resultMap
id CDATA #REQUIRED
type CDATA #REQUIRED
extends CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
>

<!ELEMENT constructor ((idArg|arg)*)>

<!ELEMENT id EMPTY>
<!ATTLIST id
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT idArg EMPTY>
<!ATTLIST idArg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
name CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
name CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
>

<!ELEMENT collection (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST collection
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
ofType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
notNullColumn CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
resultSet CDATA #IMPLIED
foreignColumn CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
fetchType (lazy|eager) #IMPLIED
>

<!ELEMENT association (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST association
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
notNullColumn CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
resultSet CDATA #IMPLIED
foreignColumn CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
fetchType (lazy|eager) #IMPLIED
>

<!ELEMENT discriminator (case+)>
<!ATTLIST discriminator
column CDATA #IMPLIED
javaType CDATA #REQUIRED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT case (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST case
value CDATA #REQUIRED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
fetchSize CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
useCache (true|false) #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
resultOrdered (true|false) #IMPLIED
resultSets CDATA #IMPLIED 
affectData (true|false) #IMPLIED
>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST selectKey
resultType CDATA #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
keyColumn CDATA #IMPLIED
order (BEFORE|AFTER) #IMPLIED
databaseId CDATA #IMPLIED
>

<!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include (property+)?>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT bind EMPTY>
<!ATTLIST bind
 name CDATA #REQUIRED
 value CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
id CDATA #REQUIRED
lang CDATA #IMPLIED
databaseId CDATA #IMPLIED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
nullable (true|false) #IMPLIED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/foreach/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.foreach.Mapper">

    <select id="getUser" resultType="org.apache.ibatis.submitted.foreach.User">
        select * from users
         WHERE id in (
        <foreach item="item" index="index" collection="friendList"
          separator="," >
          #{item.id}
        </foreach>
        )
    </select>

  <select id="countByUserList" resultType="_int" parameterType="list">
    select count(*) from users
      <where>
        id in
        <foreach item="item" collection="list" separator="," open="(" close=")">
          #{item.id, jdbcType=NUMERIC}
        </foreach>
      </where>
  </select>

  <select id="countByBestFriend" resultType="_int" parameterType="list">
    select count(*) from users
      <where>
        id in
        <foreach item="item" collection="list" separator="," open="(" close=")">
          #{item.bestFriend.id, jdbcType=NUMERIC}
        </foreach>
      </where>
  </select>

  <select id="selectWithNullItemCheck" resultType="string">
    select name from users
      <where>
        id in
        <foreach item="item" collection="list" separator="," open="(" close=")">
          <if test="item != null">
            #{item.id, jdbcType=NUMERIC}
          </if>
        </foreach>
      </where>
  </select>

  <insert id="typoInItemProperty">
    insert into users (id, name) values
    <foreach item="item" collection="list" separator=",">
        (#{item.idd}, #{item.name})
    </foreach>
  </insert>

  <select id="itemVariableConflict" resultType="_int">
    select count(*) from users where id in
    <foreach collection="ids" item="id" open="(" close=")" separator=",">
      <foreach collection="ids2" item="id">
        #{id},
      </foreach>
      #{id}
    </foreach>
    or id = #{id}
  </select>

  <select id="indexVariableConflict" resultType="_int">
    select count(*) from users where id in
    <foreach collection="idxs" index="idx" open="(" close=")" separator=",">
      <foreach collection="idxs2" index="idx">
        #{idx},
      </foreach>
      #{idx} + 2
    </foreach>
    or id = #{idx}
  </select>

  <select id="countUserWithNullableIsOmit" resultType="_int">
    select count(*) from users
    <where>
      <foreach item="item" index="index" collection="friendList" open="id in ("
               separator="," close=")">
        #{item.id}
      </foreach>
    </where>
  </select>

  <select id="countUserWithNullableIsTrue" resultType="_int">
    select count(*) from users
    <where>
      <foreach item="item" index="index" collection="friendList" nullable="true" open="id in ("
               separator="," close=")">
        #{item.id}
      </foreach>
    </where>
  </select>

  <select id="countUserWithNullableIsFalse" resultType="_int">
    select count(*) from users
    <where>
      <foreach item="item" index="index" collection="friendList" nullable="false" open="id in ("
               separator="," close=")">
        #{item.id}
      </foreach>
    </where>
  </select>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/extends_with_constructor/StudentMapper.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.extends_with_constructor.StudentMapper">
    <resultMap id="StudentMap" type="org.apache.ibatis.submitted.extends_with_constructor.Student">
           <result property="id" column="id"/>
        <result property="name" column="name"/>
        <association property="teacher" column="teacherId" select="org.apache.ibatis.submitted.extends_with_constructor.TeacherMapper.selectById"/>
    </resultMap>
    <resultMap id="StudentMapWithTeacherMap" type="org.apache.ibatis.submitted.extends_with_constructor.Student" extends="StudentMap">
        <association property="teacher" resultMap="org.apache.ibatis.submitted.extends_with_constructor.TeacherMapper.TeacherMap"/>
    </resultMap>

    <select id="selectAllWithTeacher" resultMap="StudentMapWithTeacherMap">
        SELECT id, name, teacherId
        FROM student
    </select>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/not_null_column/FatherMapper.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.not_null_column.FatherMapper">

    <resultMap id="ChildMap" type="Child">
        <result property="id" column="child_id"/>
        <result property="name" column="child_name"/>
    </resultMap>

    <resultMap id="FatherMapNoFid" type="Father">
        <id property="id" column="id"/>
        <result property="name" column="name"/>
        <collection property="children" ofType="Child" notNullColumn="child_id">
            <result property="id" column="child_id"/>
            <result property="name" column="child_name"/>
        </collection>
    </resultMap>

    <select id="selectByIdNoFid" resultMap="FatherMapNoFid" parameterType="int">
        SELECT id, name, Child.id AS child_id, Child.name AS child_name
        FROM Father
        LEFT JOIN Child ON Father.id = Child.father_id
        WHERE id = #{id}
    </select>

    <resultMap id="FatherMapFid" type="Father">
        <id property="id" column="id"/>
        <result property="name" column="name"/>
        <collection property="children" ofType="Child" notNullColumn="child_id">
            <id property="id" column="child_id"/>
            <result property="fatherId" column="id"/>
            <result property="name" column="child_name"/>
        </collection>
    </resultMap>

    <select id="selectByIdFid" resultMap="FatherMapFid" parameterType="int">
        SELECT id, name, Child.id AS child_id, Child.name AS child_name
        FROM Father
        LEFT JOIN Child ON Father.id = Child.father_id
        WHERE id = #{id}
    </select>

    <resultMap id="FatherMapWithInternalResultMap" type="Father">
        <id property="id" column="id"/>
        <result property="name" column="name"/>
        <result property="tempDateField" column="current"/>
        <collection property="children" ofType="Child" notNullColumn="child_id">
            <result property="id" column="child_id"/>
            <result property="name" column="child_name"/>
            <result property="tempDateField" column="current"/>
        </collection>
    </resultMap>

    <select id="selectByIdWithInternalResultMap" resultMap="FatherMapWithInternalResultMap" parameterType="int">
        SELECT id, name, sysdate as current, Child.id AS child_id, Child.name AS child_name
        FROM Father
        LEFT JOIN Child ON Father.id = Child.father_id
        WHERE id = #{id}
    </select>

    <resultMap id="ChildMapWithRefResultMap" type="Child">
        <result property="id" column="child_id"/>
        <result property="name" column="child_name"/>
        <result property="tempDateField" column="current"/>
    </resultMap>
    <resultMap id="FatherMapWithRefResultMap" type="Father">
        <id property="id" column="id"/>
        <result property="name" column="name"/>
        <result property="tempDateField" column="current"/>
        <collection property="children" ofType="Child" notNullColumn="child_id" resultMap="ChildMapWithRefResultMap"/>
    </resultMap>

    <select id="selectByIdWithRefResultMap" resultMap="FatherMapWithRefResultMap" parameterType="int">
        SELECT id, name, sysdate as current, Child.id AS child_id, Child.name AS child_name
        FROM Father
        LEFT JOIN Child ON Father.id = Child.father_id
        WHERE id = #{id}
    </select>

    <resultMap id="FatherMapFidMultipleNullColumns" type="Father">
        <id property="id" column="id"/>
        <result property="name" column="name"/>
        <collection property="children" ofType="Child" notNullColumn="child_id, child_name">
            <id property="id" column="child_id"/>
            <result property="fatherId" column="id"/>
            <result property="name" column="child_name"/>
        </collection>
    </resultMap>

    <select id="selectByIdFidMultipleNullColumns" resultMap="FatherMapFidMultipleNullColumns" parameterType="int">
        SELECT id, name, Child.id AS child_id, Child.name AS child_name
        FROM Father
        LEFT JOIN Child ON Father.id = Child.father_id
        WHERE id = #{id}
    </select>

    <resultMap id="FatherMapFidMultipleNullColumnsAndBrackets" type="Father">
        <id property="id" column="id"/>
        <result property="name" column="name"/>
        <collection property="children" ofType="Child" notNullColumn="{child_id, child_name}">
            <id property="id" column="child_id"/>
            <result property="fatherId" column="id"/>
            <result property="name" column="child_name"/>
        </collection>
    </resultMap>

    <select id="selectByIdFidMultipleNullColumnsAndBrackets" resultMap="FatherMapFidMultipleNullColumnsAndBrackets" parameterType="int">
        SELECT id, name, Child.id AS child_id, Child.name AS child_name
        FROM Father
        LEFT JOIN Child ON Father.id = Child.father_id
        WHERE id = #{id}
    </select>

    <resultMap id="FatherMapFidWorkaround" type="Father">
        <id property="id" column="id"/>
        <result property="name" column="name"/>
        <collection property="children" ofType="Child">
            <result property="id" column="child_id"/>
            <result property="fatherId" column="child_father_id"/>
            <result property="name" column="child_name"/>
        </collection>
    </resultMap>

    <select id="selectByIdFidWorkaround" resultMap="FatherMapFidWorkaround" parameterType="int">
        SELECT id, name, Child.id AS child_id, Child.name AS child_name, Child.father_id AS child_father_id
        FROM Father
        LEFT JOIN Child ON Father.id = Child.father_id
        WHERE id = #{id}
    </select>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/column_forwarding/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.column_forwarding.Mapper">

    <select id="getUser" parameterType="map" resultMap="userResult">
        select * from users where id=#{id}
    </select>

    <select id="getGroup" parameterType="map" resultMap="groupResult">
        select * from groups where id=#{id} and state=#{state}
    </select>

    <resultMap id="userResult"
        type="org.apache.ibatis.submitted.column_forwarding.User">
        <id column="id" property="id" />
        <result column="name" property="name" />
        <result column="state" property="state" />
        <association property="group" column="{id=group_id,state=state}" select="getGroup" javaType="org.apache.ibatis.submitted.column_forwarding.Group" />
    </resultMap>

    <resultMap id="groupResult"
        type="org.apache.ibatis.submitted.column_forwarding.Group">
        <id column="id" property="id" />
        <result column="state" property="state" />
    </resultMap>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/includes/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.includes.mapper">
  <sql id="sometable">
    ${prefix}Table
  </sql>

  <sql id="someinclude">
    <include refid="${include_target}"/>
  </sql>

  <select id="select" resultType="map">
    <include refid="someinclude">
        <property name="include_target" value="org.apache.ibatis.submitted.includes.fragments.select"/>
    </include>
    field1, field2, field3
    from
      <include refid="someinclude">
          <property name="prefix" value="Some"/>
          <property name="include_target" value="sometable"/>
      </include>
  </select>

  <select id="selectWithProperty" resultType="_int">
    <include refid="${ns}.values"/>
  </select>

  <update id="update" parameterType="map">
    <include refid="org.apache.ibatis.submitted.includes.fragments.update"/>
    <include refid="org.apache.ibatis.submitted.includes.mapper.sometable">
        <property name="prefix" value="Some"/>
    </include>
    set Field2 = #{field2,jdbcType=INTEGER},
    Field3 = #{field3,jdbcType=VARCHAR},
    where field1 = #{field1,jdbcType=INTEGER}
  </update>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/discriminator/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper
  namespace="org.apache.ibatis.submitted.discriminator.Mapper">

  <resultMap
    type="org.apache.ibatis.submitted.discriminator.Vehicle"
    id="vehicleResult">
    <id property="id" column="id" />
    <result property="maker" column="maker" />
    <discriminator javaType="int" column="vehicle_type">
      <case value="1"
        resultType="org.apache.ibatis.submitted.discriminator.Car">
        <result property="doorCount" column="door_count" />
      </case>
      <case value="2"
        resultType="org.apache.ibatis.submitted.discriminator.Truck">
        <result property="carryingCapacity"
          column="carrying_capacity" />
      </case>
    </discriminator>
  </resultMap>

  <select id="selectVehicles" resultMap="vehicleResult"><![CDATA[
    select * from vehicle order by id
  ]]></select>

  <resultMap
    type="org.apache.ibatis.submitted.discriminator.Owner"
    id="ownerResult">
    <id property="id" column="id" />
    <result property="name" column="name" />
    <discriminator javaType="string" column="vehicle_type">
      <case value="car">
        <association property="vehicle" column="vehicle_id"
          select="selectCar" />
      </case>
      <case value="truck">
        <association property="vehicle" column="vehicle_id"
          select="selectTruck" />
      </case>
    </discriminator>
  </resultMap>

  <select id="selectOwnersWithAVehicle" resultMap="ownerResult"><![CDATA[
    select id, name, vehicle_type, vehicle_id
    from owner
  ]]></select>

  <select id="selectCar"
    resultType="org.apache.ibatis.submitted.discriminator.Car"><![CDATA[
    select id, maker, door_count doorCount
    from vehicle
    where id = #{id}
  ]]></select>

  <select id="selectTruck"
    resultType="org.apache.ibatis.submitted.discriminator.Truck"><![CDATA[
    select id, maker, door_count carryingCapacity
    from vehicle
    where id = #{id}
  ]]></select>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/dml_return_types/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.dml_return_types.Mapper">

    <select id="getUser" parameterType="Integer" resultType="org.apache.ibatis.submitted.dml_return_types.User">
        select * from users where id = #{id}
    </select>

    <sql id="update">
        update users set name = #{name} where id = #{id}
    </sql>

    <update id="updateReturnsVoid" parameterType="org.apache.ibatis.submitted.dml_return_types.User">
        <include refid="update"/>
    </update>

    <update id="updateReturnsPrimitiveInteger" parameterType="org.apache.ibatis.submitted.dml_return_types.User">
        <include refid="update"/>
    </update>

    <update id="updateReturnsInteger" parameterType="org.apache.ibatis.submitted.dml_return_types.User">
        <include refid="update"/>
    </update>

    <update id="updateReturnsPrimitiveLong" parameterType="org.apache.ibatis.submitted.dml_return_types.User">
        <include refid="update"/>
    </update>

    <update id="updateReturnsLong" parameterType="org.apache.ibatis.submitted.dml_return_types.User">
        <include refid="update"/>
    </update>

    <update id="updateReturnsPrimitiveBoolean" parameterType="org.apache.ibatis.submitted.dml_return_types.User">
        <include refid="update"/>
    </update>

    <update id="updateReturnsBoolean" parameterType="org.apache.ibatis.submitted.dml_return_types.User">
        <include refid="update"/>
    </update>

</mapper>
