=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/main/resources/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!ELEMENT mapper (cache-ref | cache | resultMap* | parameterMap* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
namespace CDATA #IMPLIED
>

<!ELEMENT cache-ref EMPTY>
<!ATTLIST cache-ref
namespace CDATA #REQUIRED
>

<!ELEMENT cache (property*)>
<!ATTLIST cache
type CDATA #IMPLIED
eviction CDATA #IMPLIED
flushInterval CDATA #IMPLIED
size CDATA #IMPLIED
readOnly CDATA #IMPLIED
blocking CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)?>
<!ATTLIST parameterMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
resultMap CDATA #IMPLIED
scale CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT resultMap (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST resultMap
id CDATA #REQUIRED
type CDATA #REQUIRED
extends CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
>

<!ELEMENT constructor ((idArg|arg)*)>

<!ELEMENT id EMPTY>
<!ATTLIST id
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT idArg EMPTY>
<!ATTLIST idArg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
name CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
name CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
>

<!ELEMENT collection (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST collection
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
ofType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
notNullColumn CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
resultSet CDATA #IMPLIED
foreignColumn CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
fetchType (lazy|eager) #IMPLIED
>

<!ELEMENT association (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST association
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
notNullColumn CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
resultSet CDATA #IMPLIED
foreignColumn CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
fetchType (lazy|eager) #IMPLIED
>

<!ELEMENT discriminator (case+)>
<!ATTLIST discriminator
column CDATA #IMPLIED
javaType CDATA #REQUIRED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT case (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST case
value CDATA #REQUIRED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
fetchSize CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
useCache (true|false) #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
resultOrdered (true|false) #IMPLIED
resultSets CDATA #IMPLIED 
affectData (true|false) #IMPLIED
>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST selectKey
resultType CDATA #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
keyColumn CDATA #IMPLIED
order (BEFORE|AFTER) #IMPLIED
databaseId CDATA #IMPLIED
>

<!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include (property+)?>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT bind EMPTY>
<!ATTLIST bind
 name CDATA #REQUIRED
 value CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
id CDATA #REQUIRED
lang CDATA #IMPLIED
databaseId CDATA #IMPLIED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
nullable (true|false) #IMPLIED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/call_setters_on_nulls/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.call_setters_on_nulls.Mapper">

    <select id="getUserUnmapped" resultType="org.apache.ibatis.submitted.call_setters_on_nulls.User">
        select * from users
    </select>

    <select id="getUserInMap" resultType="map">
        select * from users
    </select>

    <select id="getUserMapped" resultMap="userMap">
        select * from users
    </select>

    <resultMap type="org.apache.ibatis.submitted.call_setters_on_nulls.User" id="userMap">
        <id property="id" column="id" />
        <result property="name" column="name" />
    </resultMap>

    <select id="getNameOnly" resultType="map">
        select name from users2
    </select>

    <select id="getNameOnlyMapped" resultMap="mapResult">
        select name from users2
    </select>

    <resultMap type="map" id="mapResult">
        <result column="name" property="name" />
    </resultMap>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/result_set_type/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.result_set_type.Mapper">

  <select id="getUserWithStatementAndUnset" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="STATEMENT">
        select * from users order by id
    </select>
  <select id="getUserWithStatementAndDefault" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="STATEMENT" resultSetType="DEFAULT">
        select * from users order by id
    </select>
  <select id="getUserWithStatementAndForwardOnly" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="STATEMENT" resultSetType="FORWARD_ONLY">
        select * from users order by id
    </select>
  <select id="getUserWithStatementAndScrollInsensitive" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="STATEMENT" resultSetType="SCROLL_INSENSITIVE">
        select * from users order by id
    </select>
  <select id="getUserWithStatementAndScrollSensitive" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="STATEMENT" resultSetType="SCROLL_SENSITIVE">
        select * from users order by id
    </select>

  <select id="getUserWithPreparedAndUnset" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="PREPARED">
        select * from users order by id
    </select>
  <select id="getUserWithPreparedAndDefault" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="PREPARED" resultSetType="DEFAULT">
        select * from users order by id
    </select>
  <select id="getUserWithPreparedAndForwardOnly" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="PREPARED" resultSetType="FORWARD_ONLY">
        select * from users order by id
    </select>
  <select id="getUserWithPreparedAndScrollInsensitive" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="PREPARED" resultSetType="SCROLL_INSENSITIVE">
        select * from users order by id
    </select>
  <select id="getUserWithPreparedAndScrollSensitive" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="PREPARED" resultSetType="SCROLL_SENSITIVE">
        select * from users order by id
    </select>

  <select id="getUserWithCallableAndUnset" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="CALLABLE">
        {call getusers()}
    </select>
  <select id="getUserWithCallableAndDefault" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="CALLABLE" resultSetType="DEFAULT">
        {call getusers()}
    </select>
  <select id="getUserWithCallableAndForwardOnly" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="CALLABLE" resultSetType="FORWARD_ONLY">
        {call getusers()}
    </select>
  <select id="getUserWithCallableAndScrollInsensitive" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="CALLABLE" resultSetType="SCROLL_INSENSITIVE">
        {call getusers()}
    </select>
  <select id="getUserWithCallableAndScrollSensitive" resultType="org.apache.ibatis.submitted.result_set_type.User"
          statementType="CALLABLE" resultSetType="SCROLL_SENSITIVE">
        {call getusers()}
    </select>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/sptests/SPMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "https://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="org.apache.ibatis.submitted.sptests.SPMapper">

  <resultMap type="org.apache.ibatis.submitted.sptests.Name" id="nameResult">
    <result column="ID" property="id"/>
    <result column="FIRST_NAME" property="firstName"/>
    <result column="LAST_NAME" property="lastName"/>
  </resultMap>

  <resultMap type="org.apache.ibatis.submitted.sptests.Name" id="nameResultLinked">
    <result column="ID" property="id"/>
    <result column="FIRST_NAME" property="firstName"/>
    <result column="LAST_NAME" property="lastName"/>
    <collection property="items" column="id" foreignColumn="name_id" resultSet="items" resultMap="itemResult"/>
  </resultMap>

  <resultMap type="org.apache.ibatis.submitted.sptests.Name" id="nameResultLinkedNoMatchingInfo">
    <result column="ID" property="id"/>
    <result column="FIRST_NAME" property="firstName"/>
    <result column="LAST_NAME" property="lastName"/>
    <collection property="items" resultSet="items" resultMap="itemResult"/>
  </resultMap>

  <resultMap type="org.apache.ibatis.submitted.sptests.Item" id="itemResult">
    <result column="ID" property="id"/>
    <result column="ITEM" property="item"/>
  </resultMap>

  <parameterMap type="map" id="testParameterMap">
    <parameter property="addend1" jdbcType="INTEGER" mode="IN"/>
    <parameter property="addend2" jdbcType="INTEGER" mode="IN"/>
    <parameter property="sum" jdbcType="INTEGER" mode="OUT"/>
  </parameterMap>

  <!-- Important things for stored procedures:
    1. Must set the statement type to CALLABLE
    2. Must use the JDBC standard escape sequence for stored procedures:
       {call xxx (parm1, parm2)}
    3. Must set the MODE of all parameters (IN, OUT, INOUT)
    4. All IN, OUT, and INOUT parameters must be a part of the
       parameterType or parameterMap (discouraged).  The only exception
       is if you are using a Map as a parameter object.  In that case you
       do not need to add OUT parameters to the map before calling, MyBatis
       will add them for you automatically.
    5. resultType or resultMap (more typically) is only used if
       the procedure returns a result set. IMPORTANT: Oracle ref
       cursors are usually returned as parameters, NOT directly
       from the stored proc.  So with ref cursors, resultMap
       and/or resultType is usually not used.
   -->

  <select id="adderAsSelect" parameterType="org.apache.ibatis.submitted.sptests.Parameter" statementType="CALLABLE">
    {call sptest.adder(
      #{addend1,jdbcType=INTEGER,mode=IN},
      #{addend2,jdbcType=INTEGER,mode=IN},
      #{sum,jdbcType=INTEGER,mode=OUT}
    )}
  </select>

  <update id="adderAsUpdate" parameterType="org.apache.ibatis.submitted.sptests.Parameter" statementType="CALLABLE">
    {call sptest.adder(
      #{addend1,jdbcType=INTEGER,mode=IN},
      #{addend2,jdbcType=INTEGER,mode=IN},
      #{sum,jdbcType=INTEGER,mode=OUT}
    )}
  </update>

  <update id="adderWithParameterMap" parameterMap="testParameterMap" statementType="CALLABLE">
    {call sptest.adder(?, ?, ?)}
  </update>

  <select id="getName" parameterType="java.lang.Integer" statementType="CALLABLE"
    resultMap="nameResult">
    {call sptest.getname(
      #{id,jdbcType=INTEGER,mode=IN})}
  </select>

  <select id="getNames" parameterType="java.util.Map" statementType="CALLABLE"
    resultMap="nameResult">
    {call sptest.getnames(
      #{lowestId,jdbcType=INTEGER,mode=IN},
      #{totalRows,jdbcType=INTEGER,mode=OUT})}
  </select>

  <select id="getNamesWithArray" parameterType="java.util.Map" statementType="CALLABLE"
    resultMap="nameResult">
    {call sptest.arraytest(
      #{ids,mode=IN,jdbcType=ARRAY},
      #{requestedRows,jdbcType=INTEGER,mode=OUT},
      #{returnedIds,mode=OUT,jdbcType=ARRAY})}
  </select>

  <select id="getNamesAndItems" statementType="CALLABLE"
    resultMap="nameResult,itemResult">
    {call sptest.getnamesanditems()}
  </select>

  <select id="getNamesAndItemsLinked" statementType="CALLABLE" resultSets="names,items" resultMap="nameResultLinked">
    {call sptest.getnamesanditems()}
  </select>

  <select id="getNamesAndItemsLinkedById" statementType="CALLABLE" resultSets="names,items" resultMap="nameResultLinkedNoMatchingInfo">
    {call sptest.getnamesanditemsbyid(#{id,jdbcType=INTEGER,mode=IN})}
  </select>

  <!-- issue #145 -->
  <select id="echoDate" parameterType="java.util.HashMap" statementType="CALLABLE">
    {call sptest.echoDate(
      #{input date,jdbcType=DATE,mode=IN},
      #{output date,jdbcType=DATE,mode=OUT}
    )}
  </select>

  <resultMap type="org.apache.ibatis.submitted.sptests.Book" id="bookAndGenreRM">
    <id column="ID" property="id" />
    <result column="NAME" property="name" />
    <association property="genre" column="genre1,genre2" foreignColumn="id1,id2" resultSet="genreRS" resultMap="genreRM" />
  </resultMap>

  <resultMap type="org.apache.ibatis.submitted.sptests.Genre" id="genreRM">
    <id column="ID1" />
    <id column="ID2" />
    <result column="NAME" property="name" />
  </resultMap>

  <select id="getBookAndGenre" statementType="CALLABLE" resultSets="bookRS,genreRS" resultMap="bookAndGenreRM">
    {call sptest.getbookandgenre()}
  </select>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/force_flush_on_select/Person.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.force_flush_on_select.PersonMapper">

    <!-- One hour cache -->
    <cache flushInterval="3600000"/>

    <resultMap id="personMap" type="Person">
        <id property="id" column="id"/>
        <result property="firstName" column="firstName"/>
        <result property="lastName" column="lastName"/>
    </resultMap>

    <select id="selectByIdFlush" resultMap="personMap" parameterType="int" flushCache="true">
        SELECT id, firstName, lastName
        FROM person
        WHERE id = #{id}
    </select>

    <select id="selectByIdNoFlush" resultMap="personMap" parameterType="int">
        SELECT id, firstName, lastName
        FROM person
        WHERE id = #{id}
    </select>

    <select id="selectAllFlush" resultMap="personMap" flushCache="true">
        SELECT id, firstName, lastName
        FROM person
        ORDER BY id
    </select>

    <select id="selectAllNoFlush" resultMap="personMap">
        SELECT id, firstName, lastName
        FROM person
        ORDER BY id
    </select>

    <update id="update" parameterType="org.apache.ibatis.submitted.force_flush_on_select.Person">
        UPDATE person set firstname = #{firstName} where id = #{id}
    </update>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/stringlist/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.stringlist.Mapper">

    <select id="getUsersAndGroups" resultMap="results">
        select * from users where id = #{id}
    </select>

    <resultMap type="org.apache.ibatis.submitted.stringlist.User" id="results">
        <id column="id" property="id"/>
        <collection property="groups" ofType="string">
            <result column="group_id"/>
        </collection>
        <collection property="roles" ofType="string">
            <result column="rol_id"/>
        </collection>
    </resultMap>

    <select id="getUsersAndGroupsMap" resultMap="mapResults">
        select * from users where id = #{id}
    </select>

    <resultMap type="map" id="mapResults">
        <id column="id" property="id" />
        <collection property="groups" ofType="string" javaType="list">
            <result column="group_id" />
        </collection>
        <collection property="roles" ofType="string" javaType="list">
            <result column="rol_id"/>
        </collection>
  </resultMap>

</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/xml_external_ref/NonFullyQualifiedNamespacePetMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="pet namespace">
    <cache />
    <resultMap type="org.apache.ibatis.submitted.xml_external_ref.Pet"
        id="petResult">
        <id property="id" column="pet_id" />
        <result property="ownerId" column="owner_id" />
        <result property="name" column="pet_name" />
    </resultMap>
    <resultMap type="org.apache.ibatis.submitted.xml_external_ref.Pet"
        id="resultWithOwner" extends="petResult">
        <association property="owner"
            javaType="org.apache.ibatis.submitted.xml_external_ref.Person"
            resultMap="person namespace.personResult" />
    </resultMap>
    <sql id="petColumnList">
        pet_id, owner_id, pet_name
    </sql>
    <select id="select" parameterType="java.lang.Integer" resultMap="resultWithOwner">
        SELECT
        <include refid="petColumnList" />
        ,
        <include refid="person namespace.personColumnList" />
        FROM pet, person where person_id = owner_id
        AND pet_id = #{id}
    </select>
</mapper>

=== xihuanxiaorang/java-study/mybatis-study/mybatis-3-mybatis-3.5.13/src/test/resources/org/apache/ibatis/submitted/xml_external_ref/NonFullyQualifiedNamespacePersonMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="person namespace">
    <cache-ref namespace="pet namespace" />
    <resultMap type="org.apache.ibatis.submitted.xml_external_ref.Person"
        id="personResult">
        <id property="id" column="person_id" />
        <result property="name" column="person_name" />
    </resultMap>
    <resultMap type="org.apache.ibatis.submitted.xml_external_ref.Person"
        id="resultWithPets" extends="personResult">
        <collection property="pets"
            ofType="org.apache.ibatis.submitted.xml_external_ref.Pet" resultMap="pet namespace.petResult" />
    </resultMap>
    <sql id="personColumnList">
        person_id, person_name
    </sql>
    <!-- Referencing a sql fragment in another file -->
    <select id="select" parameterType="java.lang.Integer" resultMap="resultWithPets">
        SELECT
        <include refid="personColumnList" />
        ,
        <include refid="pet namespace.petColumnList" />
        FROM person, pet
        WHERE person_id = #{id}
        AND person_id = owner_id
        ORDER
        BY pet_id
    </select>
    <!-- Referencing a sql fragment and a result map in another file -->
    <select id="selectPet" parameterType="java.lang.Integer"
        resultMap="pet namespace.petResult">
        SELECT
        <include refid="pet namespace.petColumnList" />
        FROM pet
        WHERE pet_id = #{id}
    </select>
</mapper>
